import React, { useState, useRef, useEffect } from 'react';
import { generateBlogContent, StructuredAIResponse } from '../services/geminiService';
import { BlogPost, CategoryType } from '../types';
import { Sparkles, Loader2, Wand2, Upload, Send, ArrowLeft, Plus, Trash2, GripVertical, AlertCircle, Save } from 'lucide-react';

interface AdminGeneratorProps {
  onPostCreated: (post: BlogPost) => void;
  onCancel: () => void;
  initialPost?: BlogPost;
}

type Step = 'config' | 'review';

// Internal types for the Draft Box Editor state
interface SectionBlock {
  id: string;
  heading: string;
  content: string;
}

interface FAQBlock {
  id: string;
  question: string;
  answer: string;
}

const AdminGenerator: React.FC<AdminGeneratorProps> = ({ onPostCreated, onCancel, initialPost }) => {
  // Step State
  const [step, setStep] = useState<Step>('config');

  // Input State
  const [topic, setTopic] = useState('');
  const [category, setCategory] = useState<CategoryType>('Tech News');
  const [tone, setTone] = useState('Informative & SEO Optimized');
  
  // Generation State
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Review/Edit State
  const [metaData, setMetaData] = useState<{
    id: string;
    title: string;
    excerpt: string;
    author: string;
    imageUrl: string;
    readTime: string;
    date: string;
    tags: string[];
    category: CategoryType;
  } | null>(null);

  // Structured Content State (The "Boxes")
  const [intro, setIntro] = useState('');
  const [sections, setSections] = useState<SectionBlock[]>([]);
  const [conclusion, setConclusion] = useState('');
  const [faqs, setFaqs] = useState<FAQBlock[]>([]);

  const fileInputRef = useRef<HTMLInputElement>(null);

  // Initialize if editing an existing post
  useEffect(() => {
    if (initialPost) {
      setStep('review');
      setMetaData({
        id: initialPost.id,
        title: initialPost.title,
        excerpt: initialPost.excerpt,
        author: initialPost.author,
        imageUrl: initialPost.imageUrl,
        readTime: initialPost.readTime,
        date: initialPost.date,
        tags: initialPost.tags,
        category: initialPost.category
      });

      // Parse Markdown Content into Blocks
      parseMarkdownToBlocks(initialPost.content);
    }
  }, [initialPost]);

  const parseMarkdownToBlocks = (fullContent: string) => {
    // This is a naive parser that assumes the structure generated by this app.
    // It looks for "## " (H2) headers to split sections.
    
    // Split by "## " (H2 headers)
    const rawParts = fullContent.split('\n## ');
    
    // 1. Introduction is usually the first part (before any ##)
    let introText = rawParts[0].trim();
    if (introText.startsWith('## Introduction')) { // Handle edge case where intro has header
       introText = introText.replace('## Introduction', '').trim();
    }
    setIntro(introText);

    const newSections: SectionBlock[] = [];
    const newFaqs: FAQBlock[] = [];
    let newConclusion = '';

    // Iterate through remaining parts
    for (let i = 1; i < rawParts.length; i++) {
        const part = rawParts[i];
        const newlineIndex = part.indexOf('\n');
        const heading = part.substring(0, newlineIndex !== -1 ? newlineIndex : part.length).trim();
        const content = part.substring(newlineIndex !== -1 ? newlineIndex : part.length).trim();

        if (heading.toLowerCase().includes('final verdict') || heading.toLowerCase().includes('conclusion')) {
            newConclusion = content;
        } else if (heading.toLowerCase().includes('frequently asked questions') || heading.toLowerCase().includes('faqs')) {
            // Parse FAQs (assuming ### Question structure)
            const faqParts = content.split('### ');
            faqParts.forEach((fp, idx) => {
                if (!fp.trim()) return;
                const faqNewline = fp.indexOf('\n');
                const q = fp.substring(0, faqNewline !== -1 ? faqNewline : fp.length).trim();
                const a = fp.substring(faqNewline !== -1 ? faqNewline : fp.length).trim();
                if (q && a) {
                    newFaqs.push({ id: `faq-${idx}`, question: q, answer: a });
                }
            });
        } else {
            // Normal Section
            newSections.push({
                id: `sec-${i}`,
                heading: heading,
                content: content
            });
        }
    }

    setSections(newSections);
    setConclusion(newConclusion);
    setFaqs(newFaqs);
  };

  // 1. GENERATE PHASE
  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!process.env.API_KEY) {
        setError("API Key missing. Please check your environment variables.");
        return;
    }

    setIsLoading(true);
    setError(null);

    try {
      const data: StructuredAIResponse = await generateBlogContent(topic, category, tone);
      
      // Default AI Image
      const imagePrompt = encodeURIComponent(`${topic} ${category} technology futuristic high quality`);
      const aiImageUrl = `https://image.pollinations.ai/prompt/${imagePrompt}?width=800&height=600&nologo=true&seed=${Date.now()}`;

      // Initialize Meta Data
      setMetaData({
        id: Date.now().toString(),
        title: data.title,
        excerpt: data.excerpt,
        author: data.author,
        imageUrl: aiImageUrl,
        readTime: '5 min read', // Placeholder, will recalculate
        date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
        tags: data.tags,
        category: category as CategoryType
      });

      // Initialize Content Boxes
      setIntro(data.introduction);
      setSections(data.sections.map((s, i) => ({ ...s, id: `sec-${i}` })));
      setConclusion(data.conclusion);
      setFaqs(data.faqs.map((f, i) => ({ ...f, id: `faq-${i}` })));

      setStep('review'); // Move to review step
    } catch (err: any) {
      setError(err.message || "Failed to generate content. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  // 2. IMAGE UPLOAD HANDLER
  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file && metaData) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setMetaData({
          ...metaData,
          imageUrl: reader.result as string // Base64 string
        });
        if (fileInputRef.current) {
          fileInputRef.current.value = ''; // Reset input so same file can be selected again
        }
      };
      reader.readAsDataURL(file);
    }
  };

  // 3. HELPER: COMPILE CONTENT TO MARKDOWN
  const compileToMarkdown = (): string => {
    let md = ``;
    
    // Intro
    md += `${intro}\n\n`;

    // Sections
    sections.forEach(sec => {
      md += `## ${sec.heading}\n${sec.content}\n\n`;
    });

    // Conclusion
    if (conclusion.trim()) {
        md += `## Final Verdict\n${conclusion}\n\n`;
    }

    // FAQs
    if (faqs.length > 0) {
      md += `## Frequently Asked Questions\n`;
      faqs.forEach(f => {
        md += `### ${f.question}\n${f.answer}\n\n`;
      });
    }

    return md;
  };

  // 4. PUBLISH PHASE
  const handlePublish = () => {
    if (metaData) {
      const fullContent = compileToMarkdown();
      const wordCount = fullContent.split(' ').length;
      
      const finalPost: BlogPost = {
        ...metaData,
        content: fullContent,
        readTime: `${Math.ceil(wordCount / 200)} min read`
      };
      
      onPostCreated(finalPost);
    }
  };

  // 5. EDITOR MANIPULATION HANDLERS
  const addSection = () => {
    setSections([...sections, { id: `new-${Date.now()}`, heading: 'New Heading', content: 'Write your content here...' }]);
  };

  const removeSection = (id: string) => {
    setSections(sections.filter(s => s.id !== id));
  };

  const updateSection = (id: string, field: 'heading' | 'content', value: string) => {
    setSections(sections.map(s => s.id === id ? { ...s, [field]: value } : s));
  };

  const updateFaq = (id: string, field: 'question' | 'answer', value: string) => {
    setFaqs(faqs.map(f => f.id === id ? { ...f, [field]: value } : f));
  };

  const removeFaq = (id: string) => {
    setFaqs(faqs.filter(f => f.id !== id));
  };

  const categories: CategoryType[] = [
    'Tech News',
    'AI News',
    'AI Tools',
    'Smartphones & Gadgets',
    'Apps',
    'Software',
    'Tutorials',
    'Reviews',
    'Deals',
    'Cybersecurity',
    'Gaming',
    'Startups & Business Tech',
    'Web & Development'
  ];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/90 backdrop-blur-sm p-4 animate-in fade-in duration-300">
      <div className="bg-white dark:bg-slate-950 rounded-2xl shadow-2xl w-full max-w-6xl overflow-hidden border border-slate-200 dark:border-slate-800 animate-in zoom-in-95 duration-300 flex flex-col h-[90vh]">
        
        {/* Header */}
        <div className="bg-white dark:bg-slate-900 p-4 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between shrink-0">
          <div className="flex items-center space-x-3">
            <div className="bg-blue-600 p-2 rounded-lg text-white">
                <Wand2 className="w-5 h-5" />
            </div>
            <div>
                <h2 className="text-lg font-bold text-slate-900 dark:text-white leading-tight">
                  {initialPost ? 'Edit Article' : 'Auto-Content Studio'}
                </h2>
                <p className="text-slate-500 dark:text-slate-400 text-xs font-medium">
                  {step === 'config' ? 'Configure Prompt' : 'Draft Box Editor'}
                </p>
            </div>
          </div>
          <button onClick={onCancel} className="text-slate-500 hover:text-slate-900 dark:hover:text-white font-medium text-sm px-4 py-1.5 rounded-full transition-all">
            Close
          </button>
        </div>

        {/* Scrollable Content Area */}
        <div className="flex-1 overflow-hidden relative">
          
          {error && (
            <div className="absolute top-4 left-4 right-4 z-10 p-4 bg-red-50 dark:bg-red-900/30 border border-red-200 dark:border-red-800 text-red-700 dark:text-red-400 text-sm rounded-xl flex items-center shadow-lg">
              <AlertCircle className="w-5 h-5 mr-2 shrink-0" />
              <p>{error}</p>
            </div>
          )}

          {/* STEP 1: CONFIGURATION */}
          {step === 'config' && (
            <div className="h-full overflow-y-auto p-8 custom-scrollbar">
              <form onSubmit={handleGenerate} className="space-y-8 max-w-2xl mx-auto py-10">
                <div className="text-center mb-10">
                  <h3 className="text-2xl font-black text-slate-900 dark:text-white mb-2">What shall we write today?</h3>
                  <p className="text-slate-500">Enter a topic and let Gemini draft a structured article for you.</p>
                </div>

                <div>
                  <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-2 uppercase tracking-wide">
                    Topic / Keyword
                  </label>
                  <input 
                    type="text" 
                    value={topic}
                    onChange={(e) => setTopic(e.target.value)}
                    placeholder="e.g. Best 5G phones under ₹20,000"
                    className="w-full px-5 py-4 rounded-xl border-2 border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-white text-lg focus:ring-4 focus:ring-blue-500/10 focus:border-blue-500 outline-none transition-all font-medium placeholder-slate-400"
                    required
                  />
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-2 uppercase tracking-wide">
                      Category
                    </label>
                    <div className="relative">
                        <select 
                        value={category}
                        onChange={(e) => setCategory(e.target.value as CategoryType)}
                        className="w-full px-4 py-3.5 rounded-xl border-2 border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-white focus:ring-4 focus:ring-blue-500/10 focus:border-blue-500 outline-none transition-all appearance-none cursor-pointer font-medium"
                        >
                        {categories.map((cat) => (
                          <option key={cat} value={cat}>{cat}</option>
                        ))}
                        </select>
                    </div>
                  </div>
                  <div>
                    <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-2 uppercase tracking-wide">
                      Tone
                    </label>
                    <div className="relative">
                        <select 
                        value={tone}
                        onChange={(e) => setTone(e.target.value)}
                        className="w-full px-4 py-3.5 rounded-xl border-2 border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-white focus:ring-4 focus:ring-blue-500/10 focus:border-blue-500 outline-none transition-all appearance-none cursor-pointer font-medium"
                        >
                        <option>Informative & SEO Optimized</option>
                        <option>Professional & Authoritative</option>
                        <option>Step-by-Step Tutorial</option>
                        <option>Unbiased Review</option>
                        </select>
                    </div>
                  </div>
                </div>

                <button 
                  type="submit" 
                  disabled={isLoading}
                  className="w-full flex items-center justify-center px-8 py-4 rounded-xl bg-blue-600 text-white font-bold hover:bg-blue-700 active:bg-blue-800 transition-all disabled:opacity-70 disabled:cursor-not-allowed shadow-xl shadow-blue-500/20 hover:shadow-2xl hover:-translate-y-1"
                >
                  {isLoading ? (
                    <>
                      <Loader2 className="w-6 h-6 mr-3 animate-spin" />
                      Generating Structure...
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-6 h-6 mr-3" />
                      Generate Draft
                    </>
                  )}
                </button>
              </form>
            </div>
          )}

          {/* STEP 2: DRAFT BOX EDITOR */}
          {step === 'review' && metaData && (
            <div className="grid grid-cols-1 lg:grid-cols-12 h-full">
              
              {/* Left Column: Metadata & Assets (3 cols) */}
              <div className="lg:col-span-3 border-r border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-900/50 overflow-y-auto custom-scrollbar p-6">
                 <h4 className="text-xs font-black text-slate-400 uppercase tracking-widest mb-6">Article Assets</h4>
                 
                 <div className="space-y-6">
                    {/* Image */}
                    <div>
                      <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-2">Featured Image</label>
                      <div className="relative group rounded-xl overflow-hidden border border-slate-300 dark:border-slate-700 bg-slate-200 dark:bg-slate-800 aspect-video">
                        <img src={metaData.imageUrl} alt="Preview" className="w-full h-full object-cover" />
                        <div className="absolute inset-0 bg-black/50 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                          <button onClick={() => fileInputRef.current?.click()} className="bg-white text-slate-900 px-3 py-1.5 rounded-lg text-xs font-bold flex items-center gap-2 hover:bg-blue-50">
                             <Upload className="w-3 h-3" /> Change
                          </button>
                          <input type="file" ref={fileInputRef} className="hidden" accept="image/*" onChange={handleFileUpload} />
                        </div>
                      </div>
                    </div>

                    {/* Title */}
                    <div>
                       <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-2">Title</label>
                       <textarea 
                        value={metaData.title}
                        onChange={(e) => setMetaData({...metaData, title: e.target.value})}
                        className="w-full px-3 py-2 text-sm rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 focus:ring-2 focus:ring-blue-500 outline-none resize-none font-bold leading-tight"
                        rows={3}
                       />
                    </div>

                    {/* Excerpt */}
                    <div>
                       <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-2">Excerpt (SEO)</label>
                       <textarea 
                        value={metaData.excerpt}
                        onChange={(e) => setMetaData({...metaData, excerpt: e.target.value})}
                        className="w-full px-3 py-2 text-xs rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 focus:ring-2 focus:ring-blue-500 outline-none resize-none text-slate-600 dark:text-slate-400"
                        rows={4}
                       />
                    </div>

                    {/* Tags */}
                    <div>
                      <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-2">Tags</label>
                      <div className="flex flex-wrap gap-2">
                        {metaData.tags.map(tag => (
                          <span key={tag} className="text-[10px] bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 px-2 py-1 rounded-md text-slate-600 dark:text-slate-400">#{tag}</span>
                        ))}
                      </div>
                    </div>
                 </div>
              </div>

              {/* Right Column: Draft Box Editor (9 cols) */}
              <div className="lg:col-span-9 bg-slate-100 dark:bg-slate-950 overflow-y-auto custom-scrollbar relative">
                 <div className="max-w-4xl mx-auto p-8 pb-32 space-y-8">
                    
                    {/* 1. INTRO BOX */}
                    <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl shadow-sm overflow-hidden group hover:border-blue-400 dark:hover:border-blue-600 transition-colors">
                       <div className="bg-slate-50 dark:bg-slate-800/50 px-4 py-2 border-b border-slate-100 dark:border-slate-800 flex justify-between items-center">
                          <span className="text-[10px] uppercase font-black tracking-widest text-slate-400">Introduction</span>
                       </div>
                       <div className="p-4">
                          <textarea 
                            value={intro}
                            onChange={(e) => setIntro(e.target.value)}
                            className="w-full min-h-[120px] bg-transparent outline-none text-slate-700 dark:text-slate-300 text-base leading-relaxed resize-y placeholder-slate-300"
                            placeholder="Write your hook here..."
                          />
                       </div>
                    </div>

                    {/* 2. DYNAMIC SECTIONS */}
                    <div className="space-y-6">
                      <div className="flex items-center justify-between">
                         <h4 className="text-xs font-black text-slate-400 uppercase tracking-widest">Body Content</h4>
                         <button onClick={addSection} className="text-xs font-bold text-blue-600 hover:text-blue-700 flex items-center gap-1 bg-blue-50 dark:bg-blue-900/20 px-3 py-1.5 rounded-full transition-colors">
                           <Plus className="w-3 h-3" /> Add Section
                         </button>
                      </div>

                      {sections.map((section, index) => (
                        <div key={section.id} className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl shadow-sm overflow-hidden group relative hover:shadow-md transition-shadow">
                           <div className="bg-slate-50 dark:bg-slate-800/50 px-4 py-3 border-b border-slate-100 dark:border-slate-800 flex justify-between items-center gap-4">
                              <div className="flex items-center gap-3 flex-1">
                                <GripVertical className="w-4 h-4 text-slate-300 cursor-move" />
                                <input 
                                  type="text" 
                                  value={section.heading}
                                  onChange={(e) => updateSection(section.id, 'heading', e.target.value)}
                                  className="bg-transparent font-bold text-slate-800 dark:text-slate-200 text-sm w-full outline-none focus:text-blue-600"
                                  placeholder="Section Heading"
                                />
                              </div>
                              <button onClick={() => removeSection(section.id)} className="text-slate-400 hover:text-red-500 transition-colors p-1">
                                <Trash2 className="w-4 h-4" />
                              </button>
                           </div>
                           <div className="p-4">
                              <textarea 
                                value={section.content}
                                onChange={(e) => updateSection(section.id, 'content', e.target.value)}
                                className="w-full min-h-[150px] bg-transparent outline-none text-slate-700 dark:text-slate-300 text-base leading-relaxed resize-y placeholder-slate-300 font-mono text-sm"
                                placeholder="Write section content here (Markdown supported)..."
                              />
                           </div>
                        </div>
                      ))}
                    </div>

                    {/* 3. CONCLUSION BOX */}
                    <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl shadow-sm overflow-hidden">
                       <div className="bg-slate-50 dark:bg-slate-800/50 px-4 py-2 border-b border-slate-100 dark:border-slate-800">
                          <span className="text-[10px] uppercase font-black tracking-widest text-slate-400">Final Verdict / Conclusion</span>
                       </div>
                       <div className="p-4">
                          <textarea 
                            value={conclusion}
                            onChange={(e) => setConclusion(e.target.value)}
                            className="w-full min-h-[100px] bg-transparent outline-none text-slate-700 dark:text-slate-300 text-base leading-relaxed resize-y"
                          />
                       </div>
                    </div>

                    {/* 4. FAQ BOXES */}
                    <div className="space-y-4">
                       <h4 className="text-xs font-black text-slate-400 uppercase tracking-widest mt-8">FAQ Section (Schema Ready)</h4>
                       {faqs.map((faq) => (
                         <div key={faq.id} className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-4 flex gap-4 items-start">
                            <div className="flex-1 space-y-2">
                               <input 
                                  value={faq.question}
                                  onChange={(e) => updateFaq(faq.id, 'question', e.target.value)}
                                  className="w-full font-bold text-sm text-slate-800 dark:text-slate-200 bg-transparent outline-none placeholder-slate-400"
                                  placeholder="Question..."
                               />
                               <textarea 
                                  value={faq.answer}
                                  onChange={(e) => updateFaq(faq.id, 'answer', e.target.value)}
                                  className="w-full text-sm text-slate-600 dark:text-slate-400 bg-transparent outline-none resize-none leading-relaxed placeholder-slate-300"
                                  rows={2}
                                  placeholder="Answer..."
                               />
                            </div>
                            <button onClick={() => removeFaq(faq.id)} className="text-slate-300 hover:text-red-500">
                               <Trash2 className="w-4 h-4" />
                            </button>
                         </div>
                       ))}
                       <button onClick={() => setFaqs([...faqs, { id: `new-faq-${Date.now()}`, question: '', answer: '' }])} className="w-full py-2 border border-dashed border-slate-300 dark:border-slate-700 rounded-xl text-xs font-bold text-slate-500 hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors">
                          + Add FAQ
                       </button>
                    </div>

                 </div>

                 {/* Sticky Footer Actions */}
                 <div className="fixed bottom-0 right-0 w-full lg:w-[calc(100%-25%)] bg-white/90 dark:bg-slate-900/90 backdrop-blur border-t border-slate-200 dark:border-slate-800 p-4 flex justify-between items-center z-50">
                    <button 
                       onClick={() => {
                         if (initialPost) onCancel(); else setStep('config');
                       }}
                       className="flex items-center text-slate-500 hover:text-slate-900 dark:hover:text-white font-bold text-sm px-4"
                    >
                       <ArrowLeft className="w-4 h-4 mr-2" /> {initialPost ? 'Cancel Edit' : 'Discard Draft'}
                    </button>
                    <div className="flex items-center gap-4">
                       <span className="text-xs text-slate-400 hidden sm:inline">All changes saved locally</span>
                       <button 
                          onClick={handlePublish}
                          className="flex items-center justify-center px-8 py-3 rounded-xl bg-green-600 text-white font-bold hover:bg-green-700 transition-all shadow-lg hover:shadow-green-500/30 hover:-translate-y-1"
                       >
                          {initialPost ? (
                              <>
                                <Save className="w-4 h-4 mr-2" /> Update Post
                              </>
                          ) : (
                              <>
                                <Send className="w-4 h-4 mr-2" /> Publish Live
                              </>
                          )}
                       </button>
                    </div>
                 </div>

              </div>

            </div>
          )}

        </div>
      </div>
    </div>
  );
};

export default AdminGenerator;